chore: Refactor Async(Postgresql/MySQL)Connection
05bit/peewee-async pull request #213
Opened 2024-04-03 13:33 UTC by Akerlay

2024-04-03 13:36 UTC, Akerlay reviewed
Here is basic call, in mysql we have await. Should we do something like asyncio.iscoroutinefunction in base class? Or we should make it abstract and make separate realizations in postgresql connection and mysql connection?

2024-04-03 13:37 UTC, Akerlay commented on peewee_async.py
>      async def release_cursor(self, cursor, in_transaction=False):
Here is basic call, in mysql we have await, but postgresql not. Should we do something like asyncio.iscoroutinefunction in base class? Or we should make it abstract and make separate realizations in postgresql connection and mysql connection?

2024-04-04 15:42 UTC, kalombos requested changes

2024-04-08 09:25 UTC, kalombos approved these changes

2024-04-08 09:28 UTC, merged